// Sample data — Race / Report / Contributor 型に沿ったプレビュー用データ
// 10件のレース（ブリーフ指定通り）+ 目的別 Report

const SAMPLE_RACES = [
  {
    title: "サハラマラソン",
    title_en: "Marathon des Sables",
    slug: "marathon-des-sables",
    country: "モロッコ",
    country_code: "MA",
    coords: [31.79, -7.09],
    continent: "アフリカ",
    distance_km: 250,
    stages: 6,
    duration_days: 7,
    start_month: 4,
    terrain: ["砂漠"],
    difficulty: 5,
    support: "self",
    organizer: "Marathon des Sables",
    participants_approx: 1200,
    entry_fee: { amount: 3500, currency: "EUR" },
    official_url: "https://www.marathondessables.com/en",
    hero_image: "https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?w=1600&q=80",
    summary: "モロッコ・サハラ砂漠を6ステージ約250kmで走破する、世界で最も有名なセルフサポート式ステージレース。",
  },
  {
    title: "コースタル・チャレンジ",
    title_en: "The Coastal Challenge",
    slug: "the-coastal-challenge",
    country: "コスタリカ",
    country_code: "CR",
    coords: [9.75, -83.75],
    continent: "北アメリカ",
    distance_km: 240,
    stages: 6,
    duration_days: 6,
    start_month: 2,
    terrain: ["ジャングル", "山岳"],
    difficulty: 4,
    support: "full",
    organizer: "Pure Trail",
    official_url: "https://thecoastalchallenge.com",
    hero_image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1600&q=80",
    summary: "コスタリカの太平洋岸を、ジャングルと山を越えながら走り抜ける6ステージ240km。湿潤と熱帯性気候が特徴。",
  },
  {
    title: "ウルトラ・レース・ルーマニア",
    title_en: "Ultra Race Romania",
    slug: "ultra-race-romania",
    country: "ルーマニア",
    country_code: "RO",
    coords: [45.94, 24.97],
    continent: "ヨーロッパ",
    distance_km: 250,
    stages: 6,
    duration_days: 7,
    start_month: 8,
    terrain: ["山岳"],
    difficulty: 5,
    support: "self",
    organizer: "Beyond Marathon",
    official_url: "https://ultra-race-romania.com",
    hero_image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1600&q=80",
    summary: "トランシルバニアの山岳地帯を6ステージ250km、自前の装備で走破するセルフサポート式レース。",
  },
  {
    title: "エベレスト・トレイル・レース",
    title_en: "Everest Trail Race",
    slug: "everest-trail-race",
    country: "ネパール",
    country_code: "NP",
    coords: [28.39, 84.12],
    continent: "アジア",
    distance_km: 170,
    stages: 6,
    duration_days: 7,
    start_month: 11,
    terrain: ["山岳"],
    difficulty: 5,
    support: "full",
    organizer: "Pure Trail",
    official_url: "https://everesttrailrace.com",
    hero_image: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1600&q=80",
    summary: "標高5,000m級を走る高地のステージレース。ヒマラヤの空気の薄さがランナーに容赦なく襲いかかる。",
  },
  {
    title: "トランス・サハラ・マラソン",
    title_en: "Trans Sahara Marathon",
    slug: "trans-sahara-marathon",
    country: "モロッコ",
    country_code: "MA",
    coords: [30.50, -5.50],
    continent: "アフリカ",
    distance_km: 138,
    stages: 4,
    duration_days: 5,
    start_month: 3,
    terrain: ["砂漠"],
    difficulty: 3,
    support: "full",
    organizer: "Trans Sahara",
    official_url: "https://transsaharamarathon.com",
    hero_image: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=1600&q=80",
    summary: "サハラ砂漠を4ステージ138kmで走るフルサポート式。ステージレース入門にも適した距離設定。",
  },
  {
    title: "ウルトラ・アフリカ・レース",
    title_en: "Ultra Africa Race",
    slug: "ultra-africa-race",
    country: "モザンビーク",
    country_code: "MZ",
    coords: [-18.67, 35.53],
    continent: "アフリカ",
    distance_km: 220,
    stages: 5,
    duration_days: 6,
    start_month: 11,
    terrain: ["その他"],
    difficulty: 4,
    support: "self",
    organizer: "RPM Sports",
    official_url: "https://ultraafricarace.com",
    hero_image: "https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=1600&q=80",
    summary: "モザンビークの海岸線とサバンナを5ステージ220km走破。インド洋を望むビーチランが特徴。",
  },
  {
    title: "ウルトラ・ボリビア・レース",
    title_en: "Ultra Bolivia Race",
    slug: "ultra-bolivia-race",
    country: "ボリビア",
    country_code: "BO",
    coords: [-16.29, -67.36],
    continent: "南アメリカ",
    distance_km: 220,
    stages: 7,
    duration_days: 8,
    start_month: 9,
    terrain: ["砂漠", "山岳"],
    difficulty: 5,
    support: "self",
    organizer: "RPM Sports",
    official_url: "https://ultraboliviarace.com",
    hero_image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=80",
    summary: "標高3,500m超のアルティプラーノを7ステージ220km。塩湖と砂漠と山岳を含む高地レース。",
  },
  {
    title: "モンゴル・トレイル・ラン",
    title_en: "Mongolia Trail Run",
    slug: "mongolia-trail-run",
    country: "モンゴル",
    country_code: "MN",
    coords: [46.86, 103.85],
    continent: "アジア",
    distance_km: 170,
    stages: 6,
    duration_days: 7,
    start_month: 8,
    terrain: ["山岳", "その他"],
    difficulty: 3,
    support: "full",
    organizer: "Mongolia Trail",
    official_url: "https://mongoliatrailrun.com",
    hero_image: "https://images.unsplash.com/photo-1516908205727-40afad9449a8?w=1600&q=80",
    summary: "モンゴルの大草原と山岳地帯を6ステージ170km走る。遊牧民の暮らしと風景の中を駆け抜ける。",
  },
  {
    title: "ザ・トラック・オーストラリア",
    title_en: "The Track Australia",
    slug: "the-track-australia",
    country: "オーストラリア",
    country_code: "AU",
    coords: [-25.27, 133.78],
    continent: "オセアニア",
    distance_km: 520,
    stages: 9,
    duration_days: 10,
    start_month: 5,
    terrain: ["砂漠"],
    difficulty: 5,
    support: "self",
    organizer: "Beyond Marathon",
    official_url: "https://thetrackoutback.com",
    hero_image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=1600&q=80",
    summary: "オーストラリアのアウトバックを9ステージ520km走破。ステージレースとしては世界最長級の距離。",
  },
  {
    title: "グランド・トゥ・グランド・ウルトラ",
    title_en: "Grand to Grand Ultra",
    slug: "grand-to-grand-ultra",
    country: "アメリカ合衆国",
    country_code: "US",
    coords: [36.86, -111.37],
    continent: "北アメリカ",
    distance_km: 275,
    stages: 6,
    duration_days: 7,
    start_month: 9,
    terrain: ["砂漠"],
    difficulty: 5,
    support: "self",
    organizer: "G2G Ultra",
    official_url: "https://www.g2gultra.com",
    hero_image: "https://images.unsplash.com/photo-1517783999520-f068d7431a60?w=1600&q=80",
    summary: "グランドキャニオン北縁から始まりザ・グランドステアケースまで、砂丘・赤岩・台地を6ステージ275kmで走破。",
  },
];

// 詳細ページ用フル情報（最初のレース：サハラマラソン）
const SAMPLE_DETAIL = {
  ...SAMPLE_RACES[0],
  gear: [
    "必携：シュラフ（−5℃対応）、ヘッドランプ、コンパス、ホイッスル",
    "必携：救急キット、サバイバルブランケット、塩タブレット",
    "推奨：ゲイター、サングラス、日焼け止め、リップクリーム",
    "推奨：軽量バックパック（30L程度）、トレッキングポール",
  ],
  schedule: [
    { day: 1, description: "33km・丘陵地帯。砂利と低い砂丘を抜けるイントロダクション。" },
    { day: 2, description: "38km・砂丘エリア。エルグ・チェビの大砂丘群を縦断。" },
    { day: 3, description: "31km・岩場と乾涸びた塩湖。日中45℃を超える区間。" },
    { day: 4, description: "82km・ロングステージ。約34時間以内のフィニッシュが課される。" },
    { day: 5, description: "42km・フルマラソンステージ。砂丘と岩盤の混合地形。" },
    { day: 6, description: "16km・表彰ゴール。最後はベルベル人の村へ凱旋。" },
  ],
  entry_flow:
    "1. 公式サイトでエントリー登録（前年の秋頃に開始）\n2. 健康診断書の提出（心電図含む）\n3. 装備チェックリストの審査\n4. 渡航・宿泊手配（主催者経由のパッケージあり）",
  videos: [
    { id: "dQw4w9WgXcQ", title: "2024年大会ハイライト" },
    { id: "abc123XYZ", title: "公式プロモーション映像" },
    { id: "xyz789ABC", title: "日本人参加者ドキュメンタリー" },
  ],
  contentHtml: `
    <p>サハラマラソン（Marathon des Sables）は、モロッコ南部のサハラ砂漠を舞台に、毎年4月に開催される世界最過酷のステージレース。1986年、フランス人のパトリック・バウアーがサハラを徒歩で横断した経験をもとに創設された。</p>
    <p>ランナーは7日間にわたって自らの食料と装備を背負って走り、与えられるのは水と簡素なテントのみ。主催側はあくまでも「コースとチェックポイントの提供者」であり、参加者は完全なセルフサポートで250kmを走破する。</p>
    <p>気温は日中40℃を超え、夜間は氷点下に達することもある。砂丘、岩盤、塩湖、乾いた河床——コースは地形のあらゆる組み合わせをランナーに突きつける。完走者の多くが「人生観が変わる」と語るのはこの過酷さゆえだ。</p>
  `,
};

// レポート（同一レースに3つの目的を網羅）
const SAMPLE_REPORTS = [
  // completion ×3
  {
    title: "初挑戦で完走を目指したサハラマラソン2024",
    slug: "mds-2024-completion-tanaka",
    race_slug: "marathon-des-sables",
    contributor: "tanaka",
    date: "2024-04-20",
    purpose: "completion",
    hero_image: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=1200&q=80",
    summary: "ウルトラ未経験から1年半の準備で挑んだサハラマラソン。完走するための装備選びと食事戦略をまとめました。",
  },
  {
    title: "40代からの初ステージレース完走記",
    slug: "mds-2024-completion-suzuki",
    race_slug: "marathon-des-sables",
    contributor: "suzuki",
    date: "2024-05-02",
    purpose: "completion",
    hero_image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&q=80",
    summary: "フルマラソンサブ4ランナーが、年齢と仕事の制約の中でどう準備を組んだか。完走できた最低限の装備と練習量。",
  },
  {
    title: "リタイア寸前から3日目で立て直した話",
    slug: "mds-2024-completion-ito",
    race_slug: "marathon-des-sables",
    contributor: "ito",
    date: "2024-05-08",
    purpose: "completion",
    hero_image: "https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?w=1200&q=80",
    summary: "2日目で足を痛め、棄権を考えた夜。テントメイトに支えられて完走まで漕ぎ着けた泥臭い記録。",
  },
  // competitive ×1
  {
    title: "サハラマラソン2024 トップ50入り戦略",
    slug: "mds-2024-competitive-sato",
    race_slug: "marathon-des-sables",
    contributor: "sato",
    date: "2024-04-22",
    purpose: "competitive",
    hero_image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&q=80",
    summary: "上位を狙うランナー向け：最軽量装備・高強度練習・現地での攻めの補給計画。",
  },
  // personal ×2
  {
    title: "写真と一緒に砂漠を旅したサハラマラソン",
    slug: "mds-2024-personal-yamada",
    race_slug: "marathon-des-sables",
    contributor: "yamada",
    date: "2024-04-25",
    purpose: "personal",
    hero_image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&q=80",
    summary: "完走順位より体験重視。カメラ片手に砂漠の風景を楽しんだ7日間の記録。",
  },
  {
    title: "テントメイト6人と作った1週間",
    slug: "mds-2024-personal-kobayashi",
    race_slug: "marathon-des-sables",
    contributor: "kobayashi",
    date: "2024-05-12",
    purpose: "personal",
    hero_image: "https://images.unsplash.com/photo-1517783999520-f068d7431a60?w=1200&q=80",
    summary: "順位は気にしない。砂漠の夜のテントで聞いた各国ランナーの話と、それぞれが走る理由。",
  },
];

const SAMPLE_CONTRIBUTORS = [
  {
    id: "tanaka",
    name: "田中 太郎",
    bio: "アマチュアランナー。フルマラソン3:30、トレラン100km完走経験あり。サハラマラソン完走。",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=300&q=80",
    contact_method: "x",
    contact_value: "https://x.com/example",
  },
  {
    id: "sato",
    name: "佐藤 麻衣",
    bio: "実業団ランナー出身。トランス・アルピーヌ、サハラマラソン上位完走。装備マニア。",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&q=80",
    contact_method: "instagram",
    contact_value: "https://instagram.com/example",
  },
];

window.SAMPLE_RACES = SAMPLE_RACES;
window.SAMPLE_DETAIL = SAMPLE_DETAIL;
window.SAMPLE_REPORTS = SAMPLE_REPORTS;
window.SAMPLE_CONTRIBUTORS = SAMPLE_CONTRIBUTORS;
